"""Loader for the 'apply directly' list — finance firms whose live listings the
scraper cannot pull (bot-walls, JS-only boards, moved feeds), so the tracker can
still point students at the firm's official careers page.

Source of truth: data/uncovered_firms.json, regenerated by the job-scraper repo
(gen_uncovered.py) after each scrape. Cached in-process; safe if the file is
missing (returns an empty list).
"""
from __future__ import annotations

import json
import logging
import os
from typing import Dict, List

logger = logging.getLogger(__name__)

_DATA_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "data",
    "uncovered_firms.json",
)

_cache: Dict[str, object] = {"mtime": None, "firms": []}


def load_uncovered_firms() -> List[Dict[str, str]]:
    """Return the list of {company, careers_url, reason}, sorted by company.

    Reloads when the file's mtime changes so a deploy that refreshes the JSON is
    picked up without a restart. Any failure yields an empty list.
    """
    try:
        mtime = os.path.getmtime(_DATA_PATH)
    except OSError:
        return []
    if _cache["mtime"] == mtime:
        return _cache["firms"]  # type: ignore[return-value]
    try:
        with open(_DATA_PATH, "r", encoding="utf-8") as fh:
            data = json.load(fh)
        firms = [
            {
                "company": (item.get("company") or "").strip(),
                "careers_url": (item.get("careers_url") or "").strip(),
                "reason": (item.get("reason") or "").strip(),
            }
            for item in data
            if item.get("company") and (item.get("careers_url") or "").startswith("http")
        ]
        firms.sort(key=lambda x: x["company"].lower())
        _cache.update(mtime=mtime, firms=firms)
        return firms
    except Exception:
        logger.exception("Failed to load uncovered_firms.json")
        return []
